### ISSUE TITLE
建议增加每日一篇英文新闻功能

### ISSUE THREAD

**Issue by cweijan** [mqycn/huile8#1]
老哥你这个扩展非常有趣, 不过自己写的代码内出现的英文都是知道意思的, 不如增加每天一篇BBC新闻, 在Vscode中学英语, 岂不快哉?

**Comment by mqycn** [comment]
> 老哥你这个扩展非常有趣, 不过自己写的代码内出现的英文都是知道意思的, 不如增加每天一篇BBC新闻, 在Vscode中学英语, 岂不快哉?

非常感谢支持

还有其他同事写的代码，调用三方库的代码

关于看英语新闻，Chrome扩展正在规划中
