### ISSUE TITLE
点击无法播放声音

### ISSUE THREAD

**Issue by P-Mz** [mqycn/huile8#10]
------- vscode版本信息 -------
版本: 1.42.1 (user setup)
提交: c47d83b293181d9be64f27ff093689e8e7aed054
日期: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

------- 插件版本 ------- 
[v0.0.9] （2020-9-8）

------- 问题 -------
点击无法播放声音

**Comment by mqycn** [comment]
Win10 测试没问题，请问是不是ghost版本。

**Comment by mqycn** [comment]
最新版本已经解决
