### ISSUE TITLE
出错 Cannot read property 'translation' of undefined

### ISSUE THREAD

**Issue by O-AN-drew-O** [mqycn/huile8#11]
打开math.js，插件提示Cannot read property 'translation' of undefined，无法展开单词列表

文件来源：https://cdnjs.cloudflare.com/ajax/libs/mathjs/7.2.0/math.min.js

![](https://gitee.com/AN_drew/picBed/raw/master/img/cannot.png)
![](https://gitee.com/AN_drew/picBed/raw/master/img/hui.png)

**Comment by mqycn** [comment]
已经记录

**Comment by mqycn** [comment]
已经修复
