### ISSUE TITLE
发音问题

### ISSUE THREAD

**Issue by dianjie** [mqycn/huile8#20]
拉了master分支的代码，使用audio播放发音的前提是要替换VS Code的[ffmpeg](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases)动态链接库，而且要每次更新 VS Code 都需重新替换

相关链接：

- [https://github.com/nondanee/vsc-netease-music](https://github.com/nondanee/vsc-netease-music)

- [https://marketplace.visualstudio.com/items?itemName=kangping.video](https://marketplace.visualstudio.com/items?itemName=kangping.video)

发现另外一款插件[cloudmusic-vscode](https://github.com/YXL76/cloudmusic-vscode)使用的应该是这个[RustAudio/rodio](https://github.com/RustAudio/rodio)来支持播放音源的，能不能参考实现一下

**Comment by mqycn** [comment]
感谢反馈，我暂时没有遇到此问题。下一个版本支持切换切换语音引擎
