### ISSUE TITLE
按钮显示问题

### ISSUE THREAD

**Issue by arpir** [mqycn/huile8#23]
![图1](https://user-images.githubusercontent.com/25816449/137596758-f7946444-7315-4819-bbdd-e4dc87407db5.png)
![图2](https://user-images.githubusercontent.com/25816449/137596776-07717f99-d2c2-4083-b87c-a9a414f50110.png)

侧边栏达到650像素宽度的时候，按钮才能显示出来。这个宽度也过宽了吧。
电脑用的big sur 11.6 

Version: 1.61.1 (Universal)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:23:30.274Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by mqycn** [comment]
升级到最新版试下，我测试问题没有复现
