### ISSUE TITLE
【bug】今天上午看了一下ECDICT表格中的单词后，单词列表就显示混乱了。

### ISSUE THREAD

**Issue by liliangrong777** [mqycn/huile8#26]
MacBook Pro (13-inch, M1, 2020)
Version: 1.72.0 (Universal)

![image](https://user-images.githubusercontent.com/58727146/194745965-d2503dcb-3457-4904-9e8b-22f2dcc242ad.png)

**Comment by YHSanSheng** [comment]
今天更新Visual Studio Code（Version: 1.72.1）后复现了此问题 之前旧版本好像是正常的
