### ISSUE TITLE
单词列表问题bug

### ISSUE THREAD

**Issue by wangmings** [mqycn/huile8#30]
# vscode 版本: 1.72.2 (Universal)

![截屏2022-10-31 下午2 32 42](https://user-images.githubusercontent.com/44308153/198947930-d7b2c77d-1169-4cb5-9a6a-3c9f9c8f00b3.png)

**Comment by mqycn** [comment]
单词列表问题已经修复，升级到0.0.13即可解决。图标问题等下个版本处理
