### ISSUE TITLE
VS Version: 1.73.0显示异常

### ISSUE THREAD

**Issue by Ghostasky** [mqycn/huile8#31]
VSCode Version: 1.73.0显示异常
解决了的师傅麻烦联系下qaq

**Comment by Ghostasky** [comment]
> VSCode Version: 1.73.0显示异常 解决了的师傅麻烦联系下qaq

ok已解决，将所有单词的json文件中的\\n替换为其他即可，比如替换为分号。

**Comment by YHSanSheng** [comment]
打扰一下 请问单词的json文件在哪个文件夹中？

**Comment by Ghostasky** [comment]
> 打扰一下 请问单词的json文件在哪个文件夹中？

C:\Users\xxxxx\.vscode\extensions\mqycn.huile8-0.0.12\dictionary\ECDICT\

**Comment by YHSanSheng** [comment]
> 

感谢 之前因为要用会了吧插件我一直都没更新vscode版本 因为只有旧版本才显示正常

**Comment by TsingYi1263** [comment]
> > VSCode Version: 1.73.0 显示异常 解决了的师傅麻痹联系下qaq
> 
> ok已经解决，将所有单词的json文件中的\n替换为其他即可，比如替换为分号。

有六百多个json文件，有什么办法能同时修改吗

**Comment by mqycn** [comment]
0.0.13版本已经修复，升级到最新版本后可以解决

**Comment by mqycn** [comment]
> > > VSCode Version: 1.73.0 显示异常 解决了的师傅麻痹联系下qaq
> > 
> > 
> > ok已经解决，将所有单词的json文件中的\n替换为其他即可，比如替换为分号。
> 
> 有六百多个json文件，有什么办法能同时修改吗

0.0.13版本已经修复，升级到最新版本后可以解决
