### ISSUE TITLE
点击单词后无法发音，安装了最新版扩展，是我使用的方式有问题吗

### ISSUE THREAD

**Issue by LinForGame** [mqycn/huile8#36]
大佬给看下~
![image](https://user-images.githubusercontent.com/20593880/208257078-342b6015-a61d-4f7c-903f-4b44576eee6a.png)

**Comment by mqycn** [comment]
预计三月底修复

**Comment by Github3362** [comment]
还是不可以，没有发音

**Comment by mqycn** [comment]
> 大佬给看下~ ![image](https://user-images.githubusercontent.com/20593880/208257078-342b6015-a61d-4f7c-903f-4b44576eee6a.png)

已经修复，请升级到 1.0.0版本
