### ISSUE TITLE
翻译完成后提示报错

### ISSUE THREAD

**Issue by liuyanhang2004** [mqycn/huile8#37]
Cannot read properties of undefined (reading 'replace')

**Comment by xiamuguizhi** [comment]
@liuyanhang2004 

我也碰到了，不过 好像是 英语单词 在代码内部 无法被读取 才这样的。  我是注释掉 出现这样的提示。

**Comment by mqycn** [comment]
预计三月底修复

**Comment by DengMingHao** [comment]
快5月底了，这个问题还是存在。这个插件是不是已经不维护了？

**Comment by mqycn** [comment]
> 快5月底了，这个问题还是存在。这个插件是不是已经不维护了？

已经修复，请升级到 1.0.0版本

**Comment by mqycn** [comment]
@xiamuguizhi @liuyanhang2004 已经修复，请升级到 1.0.0版本
