### ISSUE TITLE
点击播放读音功能失效

### ISSUE THREAD

**Issue by YHSanSheng** [mqycn/huile8#38]
VSCode1.76.0版本中(不确定是否是版本原因导致 有一段时间没用了) 点击单词播放读音功能，会出现朗读页面 但是没有发声。

**Comment by xiamuguizhi** [comment]
@YHSanSheng   我使用正常，没用任何问题。能正常朗读发声

```
版本: 1.76.1 (user setup)
提交: 5e805b79fcb6ba4c2d23712967df89a089da575b
日期: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22000
沙盒化: No

```

**Comment by YHSanSheng** [comment]
> @YHSanSheng 我使用正常，没用任何问题。能正常朗读发声
> 
> ```
> 版本: 1.76.1 (user setup)
> 提交: 5e805b79fcb6ba4c2d23712967df89a089da575b
> 日期: 2023-03-08T16:32:00.131Z
> Electron: 19.1.11
> Chromium: 102.0.5005.196
> Node.js: 16.14.2
> V8: 10.2.154.26-electron.0
> OS: Windows_NT x64 10.0.22000
> 沙盒化: No
> ```

刚更新完1.76.1版本 发现的确可以了

**Comment by xiamuguizhi** [comment]
@YHSanSheng 那就好！这个插件真的好用！纯小白，单词一个记不住，也看不懂，全靠这个插件看翻译... 

你呢？在学哪一门编程语言？
