### ISSUE TITLE
"单词朗读页面" 也集中到侧边栏 , 会不会显示效果更好?

### ISSUE THREAD

**Issue by xiamuguizhi** [mqycn/huile8#39]
我就是有点强迫症,单独多出一个标签"单词朗读页面"  挺不习惯的, 如果要朗读,就不能关了.

所以我在想 是否 可以 集中到 和侧边栏一起? 这样也不会多出一个标签? 

当然是个人建议!  最终还是看大众的意思! 

如果不行也没事!  冒昧建议,非常抱歉! 多有叨唠, 我在这里先对您说声:"对不起".

![QQ截图20230311125548](https://user-images.githubusercontent.com/19650297/224465753-a90470f1-a230-4d76-a35a-d30345049048.png)

**Comment by mqycn** [comment]
集成不了，需要借用 webview才可以，这边只能放列表

**Comment by xiamuguizhi** [comment]
@mqycn 这样啊. 是我冒昧了. 没其他问题,是我个人感觉哈, 其他人可能没什么感觉. 能用就行 哈哈!
